core/urls.py
# coding: utf-8

from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^products/$', views.product_list, name='product_list'),
    url(r'^products/add/$', views.product_create, name='product_create'),
    url(r'^products/(?P<slug>[\w-]+)/$', views.product_detail, name='product_detail'),
    url(r'^products/(?P<slug>[\w-]+)/change/$', views.product_update, name='product_update'),
    url(r'^products/(?P<slug>[\w-]+)/delete/$', views.product_delete, name='product_delete'),

    url(r'^customers/$', views.customer_list, name='customer_list'),
    url(r'^customers/add/$', views.customer_create, name='customer_create'),
    url(r'^customers/(?P<pk>\d+)/$', views.customer_detail, name='customer_detail'),
    url(r'^customers/(?P<pk>\d+)/change/$', views.customer_update, name='customer_update'),
    url(r'^customers/(?P<pk>\d+)/delete/$', views.customer_delete, name='customer_delete'),

    url(r'^orders/$', views.order_list, name='order_list'),
    url(r'^orders/add/$', views.order_create, name='order_create'),
    url(r'^orders/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    url(r'^orders/(?P<pk>\d+)/change/$', views.order_update, name='order_update'),
    url(r'^orders/(?P<pk>\d+)/delete/$', views.order_delete, name='order_delete'),
]

simplesale/urls.py
import core
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
import debug_toolbar

urlpatterns = [
    url(r'^', include('core.urls', namespace='core')),
    # url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
]


if settings.DEBUG:
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + urlpatterns

core/models.py
# coding: utf-8

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.text import slugify
from django.utils.timezone import datetime


User = get_user_model()


class Product(models.Model):
    name = models.CharField('Nome', max_length=80)
    slug = models.SlugField('Slug', unique=True)
    price = models.DecimalField(u'Preço', max_digits=4, decimal_places=2, null=True, blank=True)
    stock = models.PositiveIntegerField('Estoque', null=True, blank=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.pk:
            self._generate_slug()
        super(Product, self).save(*args, **kwargs)

    def _generate_slug(self):
        slug = self.slug or slugify(self.name)
        self.slug = slug
        i = 0
        while True:
            try:
                self.__class__.objects.get(slug=self.slug)
                i += 1
                self.slug = u'{}-{}'.format(slug, i)
            except self.__class__.DoesNotExist:
                break


class Customer(models.Model):
    _DEFAULT_GENRE_CHOICE = ('N', u'Não declarado')
    _GENRE_CHOICES = (
        _DEFAULT_GENRE_CHOICE,
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    )

    name = models.CharField('Nome', max_length=80)
    genre = models.CharField('Sexo', max_length=2, choices=_GENRE_CHOICES, default=_DEFAULT_GENRE_CHOICE[0])
    balance = models.DecimalField('Saldo', max_digits=4, decimal_places=2, null=True, blank=True, default=0)
    origin = models.CharField(
        'Origem', max_length=40, null=True, blank=True,
        help_text='De onde conhece o cliente(e.g. Bradesco, Secretaria)'
    )

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(Customer, verbose_name='Cliente')
    seller = models.ForeignKey(User, verbose_name='Vendedor')
    created_at = models.DateTimeField('Data do pedido', default=datetime.now)
    paid_at = models.DateTimeField("Data do pagamento", null=True, blank=True)
    delivery_at = models.DateTimeField("Data de entrega", null=True, blank=True, default=datetime.now)
    discount = models.DecimalField('Desconto', max_digits=4, decimal_places=2, null=True, blank=True, default=0)
    note = models.TextField('Observação', null=True, blank=True)

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        return str(self.pk)

    def get_total(self):
        total = 0
        for item in self.orderitem_set.all():
            total += item.get_total()
        if self.discount:
            total -= self.discount
        return total
    get_total.short_description = 'Total'

    def is_paid(self):
        return bool(self.pk and self.paid_at)
    is_paid.short_description = u'Pago?'

    def save(self, *args, **kwargs):
        withdraw_stock = not self.pk
        super(Order, self).save(*args, **kwargs)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name='Pedido')
    product = models.ForeignKey(Product, verbose_name='Produto')
    amount = models.PositiveIntegerField('Quantidade', default=1)

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens dos pedidos'

    def __str__(self):
        return self.product.name

    def get_total(self):
        return self.amount * self.product.price

    def save(self, *args, **kwargs):
        withdraw_stock = not self.pk
        super(OrderItem, self).save(*args, **kwargs)
        print (withdraw_stock)

core/forms.py
# coding: utf-8

from django import forms
from django_select2.forms import ModelSelect2Widget
from django.utils.timezone import datetime

from .models import Product, Customer, Order, OrderItem


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('slug',)


class OrderProductForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=OrderItem.objects.all())
    price = forms.DecimalField()
    amount = forms.IntegerField()
    discount = forms.DecimalField()
    total = forms.DecimalField(
        forms.NumberInput(
            attrs={'readonly': True}
        )
    )

    class Meta:
        model = Product
        exclude = ('slug', 'name', 'stock',)
        widgets = {
            'product': ModelSelect2Widget(queryset=OrderItem.objects.all()),
        }



class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'


class OrderForm(forms.ModelForm):
    paid = forms.BooleanField(required=False, label=u'Pago?')

    class Meta:
        model = Order
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields['paid'].initial = bool(self.instance.paid_at)

    def clean_paid(self):
        paid = self.cleaned_data['paid']
        if paid:
            self.instance.paid_at = datetime.now()
        else:
            self.instance.paid_at = None

        return self.cleaned_data['paid']


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'
        widgets = {
            'product': ModelSelect2Widget(queryset=OrderItem.objects.all()),
        }


OrderProductFormset = forms.formset_factory(OrderProductForm)

core/views/dashboard.py
# coding: utf-8

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from core.forms import ProductForm, CustomerForm, OrderForm, OrderProductFormset
from core.models import Product, Customer, Order


LoginRequiredMixin.login_url = reverse_lazy('login')


class ProductList(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'core/product/list.html'
product_list = ProductList.as_view()


class ProductCreate(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'core/product/create.html'
    success_url = reverse_lazy('core:product_list')
product_create = ProductCreate.as_view()


class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'core/product/detail.html'
product_detail = ProductDetail.as_view()


class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'core/product/update.html'
    success_url = reverse_lazy('core:product_list')
product_update = ProductUpdate.as_view()


class ProductDelete(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('core:product_list')
product_delete = ProductDelete.as_view()


class CustomerList(LoginRequiredMixin, ListView):
    model = Customer
    template_name = 'core/customer/list.html'
customer_list = CustomerList.as_view()


class CustomerCreate(LoginRequiredMixin, CreateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'core/customer/create.html'
    success_url = reverse_lazy('core:customer_list')
customer_create = CustomerCreate.as_view()


class CustomerDetail(LoginRequiredMixin, DetailView):
    model = Customer
    slug_field = 'pk'
    template_name = 'core/customer/detail.html'
customer_detail = CustomerDetail.as_view()


class CustomerUpdate(LoginRequiredMixin, UpdateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'core/customer/update.html'
    success_url = reverse_lazy('core:customer_list')
customer_update = CustomerUpdate.as_view()


class CustomerDelete(LoginRequiredMixin, DeleteView):
    model = Customer
    success_url = reverse_lazy('core:customer_list')
customer_delete = CustomerDelete.as_view()


class OrderList(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'core/order/list.html'
order_list = OrderList.as_view()


class OrderCreate(LoginRequiredMixin, CreateView):
    model = Order
    form_class = OrderForm
    formset_classes = {'product': OrderProductFormset}
    template_name = 'core/order/create.html'
    success_url = reverse_lazy('core:order_list')

    def get(self, request, *args, **kwargs):
        self.formsets = self.get_formsets(request)
        return super(OrderCreate, self).get(request, *args, **kwargs)

    def get_context_data(self):
        ctx = super(OrderCreate, self).get_context_data()
        ctx['formsets'] = self.formsets
        return ctx

    def get_formsets(self, request):
        formsets = {}
        for name, formset_class in self.formset_classes.items():
            formsets[name] = formset_class(request.POST or None)
        return formsets
order_create = OrderCreate.as_view()


class OrderDetail(LoginRequiredMixin, DetailView):
    model = Order
    slug_field = 'pk'
    template_name = 'core/order/detail.html'
order_detail = OrderDetail.as_view()


class OrderUpdate(LoginRequiredMixin, UpdateView):
    model = Order
    form_class = OrderForm
    template_name = 'core/order/update.html'
    success_url = reverse_lazy('core:order_list')
order_update = OrderUpdate.as_view()


class OrderDelete(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('core:order_list')
order_delete = OrderDelete.as_view()

core/templates/core/order/create.html
{% extends 'core/base.html' %}
{% load bootstrap3 %}

{% block css %}
{{ block.super }}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet">
{% endblock %}

{% bootstrap_messages %}

{% block main %}
<form class="form" method="post">
    {% csrf_token %}

    <div class="form-group">
      {{ formsets.product.management_form }}
      {{ formsets.product.as_table }}
    </div>
    <!-- <div class="form-group"> -->
    <!--     <label for="{{ form.items.id_for_label }}">Items</label> -->
    <!--     <table class="table"> -->
    <!--         <thead> -->
    <!--             <tr> -->
    <!--                 <th>Produto</th> -->
    <!--                 <th>Preço</th> -->
    <!--                 <th>Quantidade</th> -->
    <!--                 <th>Desconto</th> -->
    <!--                 <th>Sub-total</th> -->
    <!--             </tr> -->
    <!--         </thead> -->
    <!--         <tbody class="js-items-container"> -->

    <!--         </tbody> -->
    <!--         <a href="#" class="btn btn-default js-add-item"><i class="glyphicon glyphicon-plus-sign"></i></a> -->
    <!--     </table> -->
    <!--     <div class="col-xs-4 pull-right"> -->
    <!--         <span>Total:<span class="js-total">0</span></span> -->
    <!--     </div> -->
    <!-- </div> -->
    {%  bootstrap_form form %}
    <button type="submit" class="btn btn-default">add</button>
</form>
{% endblock %}

{% block js %}
{{ block.super }}
<script type="text/javascript">
$(document).ready(function () {

    $('.js-add-item').click(function() {
        var id = $('tbody tr').length + 1;
        var htmlString = "<tr id=\"js-item-{id}\"><td><select class=\"form-control js-item-product\"></select></td><td><input class=\"form-control js-item-price\" type=\"number\" value=\"0\"></input></td><td><input class=\"form-control js-item-amount\" type=\"number\" value=\"1\"></input></td><td><input class=\"form-control js-item-discount\" type=\"number\" value=\"0\"></input></td><td><input class=\"form-control\ js-item-total\" type=\"number\" value=\"0\"></input></td></tr>";
        htmlString = htmlString.replace('{id}', id);
        $('.js-items-container').append(htmlString);

        $('.js-item-price, .js-item-amount, .js-item-discount').change(function() {
            var item_row = $(this).closest('tr');
            var price = parseFloat(item_row.find('.js-item-price').val());
            var amount = parseInt(item_row.find('.js-item-amount').val());
            var discount = parseFloat(item_row.find('.js-item-discount').val());
            var sub_total = price * amount - discount;
            item_row.find('.js-item-total').val(sub_total);
            var total = 0;
            $('.js-item-total').each(function(i, e) {
                total += parseFloat($(e).val());
            });
            $('.js-total').text(total);
        });

    });

});
</script>
<script href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
{{ form.media.js }}
{% endblock %}

core/templates/core/order/detail.html
{% extends 'core/base.html' %}

{% block main %}
    <table class="table">
        <thead>
        <tr>
            <th>Cliente</th>
            <th>Sexo</th>
            <th>Saldo</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ object.name }}</td>
            <td>{{ object.get_genre_display }}</td>
            <td>{{ object.balance }}</td>
        </tr>
        </tbody>
    </table>
    <form method="post" action="{% url 'core:order_delete' object.pk %}">
        {% csrf_token %}
        <button class="btn btn-danger">Deletar</button>
    </form>
{% endblock %}

core/templates/core/order/list.html
{% extends 'core/base.html' %}

{% block main %}
    <a href="{% url 'core:order_create' %}" class="btn btn-default">add</a>
    <ul class="list-group">
    {% for object in object_list %}
        <li class="list-group-item"><a href="{% url 'core:order_detail' object.pk %}">{{ object }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

core/templates/core/order/update.html
{% extends 'core/base.html' %}
{% load bootstrap3 %}

{% bootstrap_messages %}

{% block main %}
<form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-default">update</button>
</form>
{% endblock %}